### ISSUE TITLE
Windows snapped to the corner leave 1 px on top and bottom

### ISSUE THREAD

**Issue by tippl** [PapirusDevelopmentTeam/arc-kde#76]
Basically just as the title says, when you snap the window to the corner it leaves a 1 px gap through which wallpaper can be seen.

Example:
![screenshot_20180130_023359](https://user-images.githubusercontent.com/2827500/35543631-61ccb1c0-0566-11e8-9b1d-d1a10ce4be1b.png)

I am using the lastest version in the Arch community repo along with the Kvantum theming engine. This has been an issue for a while, but it seems no one reported it. (or i am blind)

**Comment by varlesh** [comment]
fixed

**Comment by UncleInf** [comment]
I'm still having this pixel gap showing wallpaper. Is i because the release hasn't been made with this fix?

**Comment by varlesh** [comment]
@UncleInf Install from git and remove cache:
`rm -rf ~/.cache/plasm* ~/.cache/ico*`
restart plasma session:
`killall plasmashell`
**ALT+F2** > `plasmashell`

**Comment by pchampio** [comment]
plasmashell 5.17.2 and I sitll have this issue.
I've filled a bug on the kde issue tracker: https://bugs.kde.org/show_bug.cgi?id=389215
But I feel like it's more relevant here because the default 'Breeze' theme don't have this issue.
